version: '3.4'

services:
  db:
    image: project-with-asp-net8-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net
    ports:
      - 3308:3306
    networks:
      - udemy-network
      
  project-with-asp-net8:
    image: project-with-asp-net8
    build:
      context: .
      dockerfile: ProjectWithASPNET8\Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44380:80
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge